# -*- coding: utf-8 -*-
"""Ad.pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpRIKEFoYTT4UzwoOGKSZi4SHtpZaro1

Pandas ----> Pandas is an open-source library which is used for handle data manipulations.
"""

import pandas as pd

# Data Structure of Pandas :::::
# (1). Series  ----> It stores only values not column name and it is one-dimensional.
# (2). DataFrame ---> It store values with column name. And it is multi-dimensional.

a=pd.Series([1,2,35])
a

type(a)

a = {
    "Emp_ID": [1,2,3,4,5],
    "Name": ['Sam','Mohit','Raj','Rahul','Aniket'],
    "Department": ['IT','Sales','IT','IT','Sales'],
    "Salary": [20000,25000,30000,31000,26000]
}

type(a)

b=pd.DataFrame(a)
print(b)
print(type(b))

### Export this data into csv
b.to_csv("Emp_data.csv")

### Export this data into Excel
b.to_excel("New_Emp_data.xlsx")

#### Import the data

c = pd.read_csv("/content/Emp_data.csv")
# c

### phone data
df = pd.read_csv("/content/flipkart.csv")

df.head(4)

#student id,name,course,duration,fees
#10 rows into data frame
# expoert into csv excel
# create new repo and upload  into github
data = {
    "student_id": [101,102,103,104,105,106,107,108,109,110],
    "name": ["Amit","Riya","Rahul","Neha","Karan","Pooja","Vikas","Anjali","Rohit","Sneha"],
    "course": ["Python","Data Science","Java","Python","SQL","Machine Learning","Java","Python","SQL","Data Science"],
    "duration": ["3 months","6 months","4 months","3 months","2 months","6 months","4 months","3 months","2 months","6 months"],
    "fees": [15000,30000,20000,15000,12000,35000,20000,15000,12000,30000]
}

df = pd.DataFrame(data)

print(df)

df.to_csv("students.csv")

df.to_excel("students.xlsx")

p=pd.read_excel("/content/top10_hotels_cleaned.xlsx")
p





