# -*- coding: utf-8 -*-
"""Attrition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZmYOX-jkh87I3aZCozL3mVrrjrMh2ew
"""

import numpy as np
import pandas as pd

import plotly.graph_objects as go
import plotly.io as pio
pio.templates.default = 'plotly_white'

df=pd.read_csv('/content/Attrition - Attrition.csv')

print(df.head(2))

print(df.isnull().sum())

attr_df=df[df['Attrition']=='Yes']

attr_df

attrition_by_dpt=attr_df.groupby(['Department']).size().reset_index(name='count')

attrition_by_dpt

# create donut piechart
fig = go.Figure(data=[go.Pie(labels=attrition_by_dpt['Department'],
                             values=attrition_by_dpt['count'],
                             hole=.3,
                             marker=dict(colors=['red','green']),
                             textposition='inside')])
fig.show()

fig.update_layout(title_text='Attrition by Department')
fig.show()

fig.update_layout(title='Attrition by Department')
fig.show()

attr_edu=df.groupby(['EducationField']).size().reset_index(name='count')

attr_edu

fig=go.Figure(data=[go.Pie(
    labels=attr_edu['EducationField'],
    values=attr_edu['count'],
    hole=.3,
    marker=dict(colors=['red','green','darkblue']),
    textposition='inside'
)])
fig.update_layout(title='Attrition by EducationField')
fig.show()

"""WE SEE EMPLOYEE WITH LIFE SCIENCE"""

attrition_by=attr_df.groupby(['YearsAtCompany']).size().reset_index(name='count')
attrition_by

attrition_by=attr_df.groupby(['YearsSinceLastPromotion']).size().reset_index(name='count')
attrition_by

# employee who donot get promotion percentage by gender
attrition_by=attr_df.groupby(['Gender']).size().reset_index(name='count')
attrition_by

fig=go.Figure(data=[go.Pie(
    labels=attrition_by['Gender'],
    values=attrition_by['count'],
    hole=.3,
    marker=dict(colors=['red','green']),
    textposition='inside'
)])
fig.update_layout(title='Attrition by Gender')
fig.show()

# higher attrition
import plotly.express as px

fig=px.scatter(df,x='Age',y='MonthlyIncome',color='Attrition',
               trendline='ols')
fig.update_layout(title=' Age vs MonthlyIncome by attrition')
fig.show()





